import { type MetadataRoute } from "next";

/**
 * `/robots.txt` — tells crawlers the whole site is open for indexing and points
 * them at the sitemap. The interactive terminal is a single-page app, so there
 * is nothing to disallow; the machine-readable source lives at `/llms.txt`.
 *
 * Generated by Next's metadata route so the sitemap URL always resolves to the
 * canonical production origin.
 */
const SITE_URL = "https://headingfwd.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
